FROM golang:1-bookworm AS builder

# RUN apt-get update && apt-get install -y --no-install-recommends sqlite3 && apt-get clean

# WORKDIR /app

COPY . .

RUN go install && \
    go build -o /go-books

FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends sqlite3 ca-certificates && \
    apt-get clean

COPY --from=builder /go-books /go-books

EXPOSE 8080

CMD ["/go-books"]
